Repository LikeLion-KNU/knufest-frontend, pull requests merged in 2024-05, with the labels that each got.

#2 environment: 프로젝트 세팅
  package.json
  pnpm-lock.yaml
  src/App.css
  src/index.css
  tsconfig.json
  vite.config.ts
Labels: 🌇 Environment

#4 메인화면 기본 틀 구현
  index.html
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/app.styled.ts
  src/assets/hapuruna.png
  src/assets/main_page.jpg
  src/assets/react.svg
  src/components/Footer.tsx
  src/components/HomePage.tsx
  src/components/Navigation.tsx
  src/index.css
  src/main.tsx
  src/styles/footer.styled.ts
  src/styles/homepage.styled.ts
  src/styles/navigation.styled.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#14 메인 페이지 버그 수정
  package.json
  pnpm-lock.yaml
  src/components/display/Countdown.styled.ts
  src/components/display/Countdown.tsx
  src/components/layout/Footer.styled.ts
  src/components/layout/Footer.tsx
  src/components/navigation/Navigation.styled.ts
  src/components/navigation/Navigation.tsx
  src/components/typography/Text.tsx
  src/pages/HomePage.styled.ts
Labels: 👹 BugFix

#24 타임테이블 페이지 구현
  pnpm-lock.yaml
  src/assets/DMSans-Medium.ttf
  src/components/display/DateSelector.styled.ts
  src/components/display/DateSelector.tsx
  src/components/display/ShowDate.styled.ts
  src/components/display/ShowDate.tsx
  src/components/display/TimeTableSection.styled.ts
  src/components/display/TimeTableSection.tsx
  src/components/layout/MainContent.ts
  src/components/layout/MainLayout.tsx
  src/components/navigation/Navigation.styled.ts
  src/components/typography/Paragraph.tsx
  src/constants/contributors.json
  src/constants/timetable.json
  src/pages/BoothListPage.styled.ts
  src/pages/BoothListPage.tsx
  src/pages/ContributorPage.styled.ts
  src/pages/ContributorPage.tsx
  src/pages/HomePage.styled.ts
  src/pages/HomePage.tsx
  src/pages/SpecialGuestPage.styled.ts
  src/pages/SpecialGuestPage.tsx
  src/pages/TimeTablePage.styled.ts
  src/pages/TimeTablePage.styled.tsx
  src/pages/TimeTablePage.tsx
  src/styles/globals.ts
  src/utils/timetableUtils.ts
Labels: ✨ Feature

#26 배포 시 폰트 적용되지 않는 현상
  public/fonts/Blinker-SemiBold.ttf
  public/fonts/DMSans-Medium.ttf
  public/fonts/MesloLGS-NF-Bold.ttf
  src/styles/globals.ts
Labels: 👹 BugFix

#27 Feature/#6
  src/components/display/BoothInfo.styled.ts
  src/components/display/BoothInfo.tsx
  src/pages/BoothDetailPage.styled.tsx
Labels: ✨ Feature

#31 메인 페이지 아닌 경우에 Navigation 색 변경되도록 구현
  src/assets/hapuruna.png
  src/components/display/BoothInfo.tsx
  src/components/navigation/Navigation.styled.ts
  src/components/navigation/Navigation.tsx
Labels: 👹 BugFix

#33 타임테이블 데이터 수정
  src/assets/jeonhangil.webp
  src/components/display/TimeTableSection.styled.ts
  src/constants/timetable.json
  src/pages/SpecialGuestPage.styled.ts
  src/pages/SpecialGuestPage.tsx
  src/pages/TimeTablePage.styled.ts
  src/pages/TimeTablePage.tsx
  src/utils/timetableUtils.ts
Labels: ✨ Feature

#35 메인 페이지 카운트다운 수정
  src/components/display/Countdown.tsx
  src/constants/timetable.json
  src/hooks/useCountdown.ts
  src/hooks/useFestivalCountdown.ts
  src/pages/HomePage.tsx
Labels: ✨ Feature

#45 메인페이지 버튼 추가, api timeout 제거
  src/components/display/ButtonList.tsx
  src/components/forms/Button.tsx
  src/config/api.ts
Labels: ✨ Feature

#48 feat: DateSelector 컴포넌트가 해당 날짜에 자동으로 focus 되도록 구현
  src/constants/timetable.json
  src/hooks/useActiveDate.ts
  src/pages/SpecialGuestPage.tsx
  src/pages/TimeTablePage.tsx
Labels: ✨ Feature
